name: Build Docker

on: 
  push:
    branches:
      - 'dev'

jobs:
    build:
        runs-on: ubuntu-latest

        services:
          mariadb:
            image: mariadb:latest
            ports:
              - 3306
            env:
              MYSQL_ROOT_PASSWORD: SuperSecretPassword
              MYSQL_DATABASE: vaulttube
              MYSQL_USER: vaulttube
              MYSQL_PASSWORD: SuperSecretPassword
            options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: Verify Database
            env:
              PORT: ${{ job.services.mariadb.ports[3306] }}
            run: |
              while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
              sleep 1
              done 
          - name: Setup PyTest and Deps
            run: |
              apt update && apt install libmariadb-dev
              pip install -r requirements.txt
              pip install pytest
          - name: Run Tests
            run: |
              python -m pytest -v tests
          - name: "docker hub login"
            uses: docker/login-action@v1
            with: 
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
          - name: "build and push"
            uses: docker/build-push-action@v2
            with: 
              context: .
              push: true
              tags: dyslexicjedi/vaulttube:dev, dyslexicjedi/vaulttube:${{github.run_number}}