name: Build Docker

on: 
  push:
    branches:
      - 'dev'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: Setup Dependencies
            run: |
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Run Tests
            run: |
              python -m pytest -v --cov=app tests
          - name: "docker hub login"
            uses: docker/login-action@v1
            with: 
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
          - name: "build and push"
            uses: docker/build-push-action@v2
            with: 
              context: .
              push: true
              tags: dyslexicjedi/vaulttube:dev, dyslexicjedi/vaulttube:${{github.run_number}}